# Techniques of Integration

<!-- ## Integration by Parts -->

## Integrations of trigonometric functions

When evaluating integrations of trigonometric functions, one idea is to reduce the total degree (power) of trigonometric functions using trigonometric identities.

In Maple, you may use the command `combine` to rewrite the expression.

```{example}

Rewrite $\cos^4x$ into an expression with single terms and evaluate the integral $\int \cos^4x\mathrm{d} x$.

```

```{solution}
<br>

    # combine terms into a single term
    combine((cos(x))^4)
    # use DiffTutor to evaluate the integral of the resulting function.
    with(Student[Calculus1])
    IntTutor(%, x)

```

You may compare the above solution with the solution given by `IntTutor((cos(x))^4, x)`.

```{exercise}

Evaluate the integral
$$
\int \tan ^{5} x \mathrm{d} x
$$

```

```{exercise}

Evaluate the integral
$$
\int \sin 5 x \sin^2 x \mathrm{d} x
$$

```

## Trigonometric Substitution

Surely, you may learn some trigonometric substitution tricks using `IntTutor`.

Here I want to introduce another useful command which when integrating functions, we may need to complete a square and then do a substitution. In Maple, we can complete squares using the command `CompleteSquare(f, x)` which supported by the package `Student[Precalculus]`.

```{example}

Evaluate the integral
$$
\int\dfrac{1}{x^2+x+1} \mathrm{d} x.
$$

```

```{solution}
<br>

We first complete the square for the denominator.

    #load package Student[Precalculus]
    with(Student[Precalculus])
    #Complete square for the denominator
    CompleteSquare(x^2+x+1, x)

Now you may try `DiffTutor` and/or evaluate it by hand.

    #load package Student[Calculus1]
    with(Student[Calculus1])
    DiffTutor(1/%, x)

```

```{exercise}

Evaluate the integral
$$
\int \sqrt{3+2 x-x^{2}} \mathrm{d} x
$$

```

```{exercise}

Evaluate the integral
$$
\int_{0}^{\pi / 2} \frac{\cos t}{\sqrt{1+\sin ^{2} t}} \mathrm{d} t
$$

```

## Integrations  of Rational Functions by Partial Fractions

In Maple, we can factor a polynomial using the command `factor(polynomial)` or find partial fraction decomposition using  `convert(function, parfrac)`.

```{example}

Find the sum of partial fractions for the rational function
$$
f(x)=\frac{x^3+4x+3}{x^4+5x^2+4}
$$

```

```{solution}
<br>
This can be done easily in Maple:

    # use the command convert
    convert((x^3+4*x+3)/(x^4+5x^2+4), parfrac)

```

```{exercise}

Find the sum of partial fractions for the rational function
$$
f(x)=\frac{x^{4}}{\left(x^{2}-x+1\right)\left(x^{2}+2\right)^{2}}.
$$

```

```{exercise}

Find the sum of partial fraction and evaluate the integral

$$
\int \frac{2}{3x^{2}+2x-1} \mathrm{d} x
$$

```

```{exercise}

Find the sum of partial fraction and evaluate the integral

$$
\int \frac{x^{3}+6 x-2}{x^{4}+6 x^{2}} \mathrm{d} x
$$

```

```{exercise}

Find the sum of partial fraction and evaluate the integral

$$
\int \frac{\sin x}{\cos ^{2} x-3 \cos x} d x
$$

```
